"""Pins the contract of GET /bills/outcomes/by-bill — the per-bill outcome index the static bill
pages are built from ("What this law has produced").

Two properties, and they pull in opposite directions, which is why both are pinned:

  UNGATED. Every bill page is generated by an ANONYMOUS build. A capability dependency here wouldn't
    paywall the block, it would delete it from the HTML for everyone, including crawlers. The gate
    this route lives under is breadth-not-depth: the cross-bill table stays on CAP_INSIGHTS_IMPACT.

  UNCAPPED, but reviewed-only. /bills/outcomes caps an unentitled caller at OUTCOME_TEASER_LIMIT to
    hold back the curated table; inheriting that cap here would mean an arbitrary handful of bills
    got the block and the rest silently didn't. The teaser is a list-length gate, not a per-bill one.
    `reviewed` is the line that stays: unvetted candidates from propose_bill_outcomes.py are never
    public, on any surface.
"""
import inspect

from app.api import bills as bills_mod


def test_route_is_registered_ahead_of_the_bill_id_catch_all():
    from app.main import app

    paths = [getattr(r, "path", "") for r in app.routes]
    assert "/bills/outcomes/by-bill" in paths
    # /bills/{bill_id} matches a single segment so it can't shadow this, but the two-segment literal
    # must still be declared before the one-segment literal it shares a prefix with.
    assert paths.index("/bills/outcomes/by-bill") < paths.index("/bills/{bill_id}")


def test_takes_no_capability_dependency():
    """An entitlement parameter here would blank the block on every statically-built page."""
    params = inspect.signature(bills_mod.bill_outcomes_by_bill).parameters
    assert list(params) == ["db"], f"unexpected parameters: {list(params)}"


def test_filters_to_reviewed_rows_that_name_a_bill_and_applies_no_teaser_cap():
    src = inspect.getsource(bills_mod.bill_outcomes_by_bill)
    assert "reviewed.is_(True)" in src, "unvetted candidates must never reach a public page"
    assert "bill_id.isnot(None)" in src, "an outcome with no bill has no page to render on"
    assert "OUTCOME_TEASER_LIMIT" not in src and ".limit(" not in src, (
        "a cap here would give an arbitrary few bills the impact block and silently starve the rest"
    )


def test_index_is_keyed_by_string_ids():
    """JSON object keys are strings; the page looks rows up with String(bill.id). A key typed as int
    here would serialize fine and miss on every lookup."""
    src = inspect.getsource(bills_mod.bill_outcomes_by_bill)
    assert "str(row.bill_id)" in src
